/* Generated by gbrecomp */
#ifndef tlozooa_H
#define tlozooa_H

#include "gbrt.h"

const GBConfig* tlozooa_default_config(void);
void tlozooa_run(GBContext* ctx);
void tlozooa_init(GBContext* ctx);
int tlozooa_main(int argc, char* argv[]);

#endif
